# Generated by cpputils-cmake.
include /home/abo0ody/workspace/opencv/portaudio/build/CMakeFiles/TestAudio.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} -S ${CHK_SOURCES}